// <auto-generated />
using Final_project.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_project.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_project.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Products used for maintaining and improving the health and appearance of the skin",
                            Name = "Skin Care"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = " Products designed to cleanse, condition, and style hair",
                            Name = "Hair Care"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Items used for various office tasks and organization",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Apparel items worn for various occasions",
                            Name = "Clothing"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Written or printed works that are bound together",
                            Name = "Books"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Edible treats and drinks.",
                            Name = "Sweets and Beverages"
                        });
                });

            modelBuilder.Entity("Final_project.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "A product used to remove dirt, oil, and impurities from the skin",
                            ImagePath = "synobar-cleanser.jpg",
                            Price = 320m,
                            Quantity = 5m,
                            Title = "Cleanser"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "A product designed to hydrate and lock in moisture for the skin.",
                            ImagePath = "Moisturizer.jpg",
                            Price = 100m,
                            Quantity = 45m,
                            Title = "Moisturizer"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "A product that protects the skin from harmful UV rays of the sun.",
                            ImagePath = "Sunscreen.jpg",
                            Price = 490m,
                            Quantity = 18m,
                            Title = "Sunscreen"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "A product used for cleaning the hair and scalp",
                            ImagePath = "شامبو-بابيلز.jpg",
                            Price = 190m,
                            Quantity = 8m,
                            Title = "Shampoo"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "A concentrated treatment used to address specific hair concerns such as frizz or dryness",
                            ImagePath = "serum.jpg",
                            Price = 235m,
                            Quantity = 15m,
                            Title = "Serum"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "A product used to moisturize and detangle the hair after shampooing.",
                            ImagePath = "conditioners.jpg",
                            Price = 322m,
                            Quantity = 100m,
                            Title = "Conditioner"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Description = " A styling product or treatment for the hair that provides hold or hydration.",
                            ImagePath = "cream.jpg",
                            Price = 212m,
                            Quantity = 53m,
                            Title = "Cream"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Description = "A product used to nourish and add shine to the hair.",
                            ImagePath = "oil.jpg",
                            Price = 192m,
                            Quantity = 95m,
                            Title = "Hair Oil"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Description = "A tool used for detangling and styling hai",
                            ImagePath = "comb.jpg",
                            Price = 422m,
                            Quantity = 45m,
                            Title = "Comb"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 3,
                            Description = "Writing instruments used for jotting down notes or documents.",
                            ImagePath = "Pen.jpg",
                            Price = 10m,
                            Quantity = 10m,
                            Title = "Pen"
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3,
                            Description = "Books with blank or lined pages for writing and taking notes.",
                            ImagePath = "NoteBook.jpg",
                            Price = 22m,
                            Quantity = 11m,
                            Title = "Notebook"
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3,
                            Description = "Compact devices used for printing documents.",
                            ImagePath = "smallPrinter.jpg",
                            Price = 2200m,
                            Quantity = 15m,
                            Title = "Small Printer"
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3,
                            Description = "Devices used for performing mathematical calculations.",
                            ImagePath = "Calculator.jpg",
                            Price = 422m,
                            Quantity = 85m,
                            Title = "Calculator"
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3,
                            Description = "Tools used for measuring or drawing straight lines.",
                            ImagePath = "ruler.jpg",
                            Price = 12m,
                            Quantity = 155m,
                            Title = "Ruler"
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            Description = "A tool used for removing pencil marks from paper.",
                            ImagePath = "eraser.jpg",
                            Price = 7m,
                            Quantity = 75m,
                            Title = "Eraser"
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 3,
                            Description = "A container used to organize and carry writing instruments",
                            ImagePath = "Pencil Case.jpg",
                            Price = 35m,
                            Quantity = 60m,
                            Title = "Pencil Case"
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4,
                            Description = "A garment worn on the upper body, usually with sleeves and a collar.",
                            ImagePath = "Shirt.jpg",
                            Price = 420m,
                            Quantity = 15m,
                            Title = "Shirt"
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4,
                            Description = "A one-piece garment worn by women or girls, often extending from the shoulders to the knees or lower.",
                            ImagePath = "dress.jpg",
                            Price = 675m,
                            Quantity = 16m,
                            Title = "Dress"
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 4,
                            Description = "A garment that hangs from the waist and covers part or all of the legs.",
                            ImagePath = "skirt.jpg",
                            Price = 450m,
                            Quantity = 20m,
                            Title = "Skirt"
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 4,
                            Description = " Garments worn on the lower body, typically covering both legs separately.",
                            ImagePath = "pants.jpg",
                            Price = 430m,
                            Quantity = 17m,
                            Title = "Pants"
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 4,
                            Description = "Footwear designed to protect and provide comfort for the feet.",
                            ImagePath = "shoes.jpg",
                            Price = 320m,
                            Quantity = 19m,
                            Title = "Shoes"
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 4,
                            Description = " Pieces of cloth worn around the neck and Head for warmth and covering the Hair.",
                            ImagePath = "khimar.jpg",
                            Price = 175m,
                            Quantity = 155m,
                            Title = "khimar hijab"
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 4,
                            Description = "A loose- fitting upper garment worn by women.",
                            ImagePath = "blouse.jpg",
                            Price = 375m,
                            Quantity = 65m,
                            Title = " Blouse"
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 5,
                            Description = "هي رواية من تأليف الكاتب المصري عمرو عبد الحميد صدرت كنسخة أولى سنة 2010 وأعادت عصير الكتب للنشر والتوزيع إصدارها سنة 2015.",
                            ImagePath = "أرض زيكولا.jpg",
                            Price = 100m,
                            Quantity = 25m,
                            Title = "أرض زيكولا"
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 5,
                            Description = "كتاب جلسات نفسية يأتي ليكون رفيقك في رحلة التعامل الصحيح مع الذات، ويقدم لك الأدوات والتقنيات التي تحتاجها لفهم ومعالجة مشكلاتك النفسية بطرق إيجابية وموجهة، وتحسين التواصل مع نفسك وفهم أعمق للعواطف والأفكار التي تؤثر فيك.",
                            ImagePath = "جلسات-نفسية.jpg",
                            Price = 80m,
                            Quantity = 35m,
                            Title = " Psychological Sessions"
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 5,
                            Description = "حسب علم النفس هي حالة وجدانية سلوكية، معناها أن يتصرف المرء بلا اهتمام في شؤون حياته أو حتى الأحداث العامة كالسياسة وإن كان هذا في غير صالحه.",
                            ImagePath = "فن اللامبالاة.jpg",
                            Price = 80m,
                            Quantity = 45m,
                            Title = "فن اللامبالاة"
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 5,
                            Description = "A book about developing effective habits",
                            ImagePath = "العادات.jpg",
                            Price = 132m,
                            Quantity = 55m,
                            Title = "The Most Effective Atomic Habits"
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 5,
                            Description = " A book about personal finance and investing",
                            ImagePath = "rich DAD poor DAD.jpg",
                            Price = 122m,
                            Quantity = 65m,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 5,
                            Description = "Magazines featuring Disney's Mickey Mouse.",
                            ImagePath = "مجلة ميكي.jpg",
                            Price = 110m,
                            Quantity = 75m,
                            Title = "Mickey Magazines"
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 5,
                            Description = "في كتاب رسائل من القرآن يتتبع أدهم شرقاوي بعض آيات من القرآن الكريم تشفي القلوب وتطفئ نيرانها المشتعلة من آلام الحياة وهمومها المختلفة",
                            ImagePath = "رسائل من القرآن.jpg",
                            Price = 189m,
                            Quantity = 85m,
                            Title = "رسائل من القرآن"
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 5,
                            Description = "يناقش الكتاب وبشكل مباشر المشاكل التي يواجهها الإنسان سواء في مواقفه اليومية، أو المشاكل الحياتية العامة",
                            ImagePath = "La_Tahzan.jpg",
                            Price = 169m,
                            Quantity = 95m,
                            Title = "لا تحزن"
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 6,
                            Description = "Traditional cakes prepared for the celebration of Eid.",
                            ImagePath = "كحك.jpg",
                            Price = 689m,
                            Quantity = 55m,
                            Title = "Eid Cake: "
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 6,
                            Description = "Simple, unflavored biscuits or cookies.",
                            ImagePath = "biscutes.jpg",
                            Price = 150m,
                            Quantity = 35m,
                            Title = "Plain Biscuits: "
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 6,
                            Description = "Biscuits flavored with or coated in chocolate.",
                            ImagePath = "Choc.jpg",
                            Price = 68m,
                            Quantity = 25m,
                            Title = "Chocolate Biscuits: "
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 6,
                            Description = "A dessert made with cream cheese, typically on a graham cracker crust.",
                            ImagePath = "cheesecake.jpg",
                            Price = 100m,
                            Quantity = 15m,
                            Title = "Cheesecake: "
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 6,
                            Description = "A rich chocolate cake with a gooey center.",
                            ImagePath = "Molten-Chocolate-Cake.jpg",
                            Price = 70m,
                            Quantity = 51m,
                            Title = "Molten Cake: "
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 6,
                            Description = " A baked good with a grid pattern, often served with toppings.",
                            ImagePath = "Wafel.jpg",
                            Price = 80m,
                            Quantity = 58m,
                            Title = "Waffles:"
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 6,
                            Description = "Coffee served cold with ice.",
                            ImagePath = "icedcoffee.jpg",
                            Price = 48m,
                            Quantity = 36m,
                            Title = "Iced Coffee: "
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 6,
                            Description = "A warm beverage made with cocoa powder and milk.",
                            ImagePath = "Hot-Chocolate-3.jpg",
                            Price = 80m,
                            Quantity = 51m,
                            Title = "Hot Chocolate: "
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 6,
                            Description = " A beverage made by infusing tea leaves in hot water.",
                            ImagePath = "tea.jpg",
                            Price = 15m,
                            Quantity = 78m,
                            Title = "Tea:"
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 6,
                            Description = " A strong, thick coffee made using finely ground coffee beans.",
                            ImagePath = "Turk.jpg",
                            Price = 35m,
                            Quantity = 95m,
                            Title = "Turkish Coffee:"
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 6,
                            Description = " A coffee style known for its rich and aromatic flavor.",
                            ImagePath = "french cofee.jpg",
                            Price = 40m,
                            Quantity = 45m,
                            Title = "French Coffee::"
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 6,
                            Description = " A beverage or flavoring made from anise seeds. ",
                            ImagePath = "ينسون.jpg",
                            Price = 25m,
                            Quantity = 72m,
                            Title = "Anise:"
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 6,
                            Description = "A refreshing herb used in beverages and cooking.",
                            ImagePath = "Mint.jpg",
                            Price = 25m,
                            Quantity = 100m,
                            Title = " Mint: :"
                        });
                });

            modelBuilder.Entity("Final_project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "fatma@gmail.com",
                            FirstName = "Fatma_alZahraa",
                            LastName = "Mohamed",
                            Password = "123abc"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Asmaa@Yahoo.com",
                            FirstName = "Asmaa",
                            LastName = "mahmoud",
                            Password = "456def"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "Hana@mail.com",
                            FirstName = "Hana",
                            LastName = "Dawood",
                            Password = "789ghi"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "Alaa@gmail.com",
                            FirstName = "Alaa",
                            LastName = "Ali",
                            Password = "101112jkl"
                        });
                });

            modelBuilder.Entity("Final_project.Models.Product", b =>
                {
                    b.HasOne("Final_project.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Final_project.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
